-- Workspace persistence schema for JuridiqueSN backend.
-- Run this in Supabase SQL editor (project database).

create table if not exists public.workspace_users (
  user_id text primary key,
  email text null,
  clerk_username text null,
  display_name text null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create index if not exists workspace_users_email_idx
  on public.workspace_users (email);

create table if not exists public.workspace_consultations (
  user_id text not null,
  id text not null,
  question text not null default '',
  answer text not null default '',
  status text not null default 'done',
  finish_reason text not null default '',
  rag_note text not null default '',
  source_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, id)
);

create index if not exists workspace_consultations_user_updated_idx
  on public.workspace_consultations (user_id, updated_at desc);

create table if not exists public.workspace_notes (
  user_id text primary key,
  notes text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.workspace_files (
  user_id text not null,
  id text not null,
  name text not null,
  size bigint not null default 0,
  added_at timestamptz not null default now(),
  primary key (user_id, id)
);

create index if not exists workspace_files_user_added_idx
  on public.workspace_files (user_id, added_at desc);

create table if not exists public.workspace_templates (
  user_id text not null,
  id text not null,
  name text not null,
  category text not null default 'Modeles personnalises',
  domain text not null default 'Personnalise',
  branch text not null default 'Document juridique',
  complexity text not null default 'Simple',
  description text not null default '',
  legal_refs jsonb not null default '[]'::jsonb,
  required_fields jsonb not null default '[]'::jsonb,
  optional_fields jsonb not null default '[]'::jsonb,
  sections jsonb not null default '[]'::jsonb,
  warning text not null default '',
  fields jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, id)
);

create index if not exists workspace_templates_user_updated_idx
  on public.workspace_templates (user_id, updated_at desc);

create table if not exists public.workspace_guest_qa_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  auth_mode text not null default '',
  user_id text null,
  user_email text null,
  user_name text null,
  user_username text null,
  client_ip text not null default '',
  question text not null default '',
  answer text not null default '',
  rag_note text not null default '',
  finish_reason text not null default '',
  rag_source_count integer not null default 0,
  provider text not null default '',
  model text not null default '',
  metadata jsonb not null default '{}'::jsonb
);

alter table if exists public.workspace_guest_qa_logs
  add column if not exists auth_mode text not null default '';

alter table if exists public.workspace_guest_qa_logs
  add column if not exists user_id text null;

alter table if exists public.workspace_guest_qa_logs
  add column if not exists user_email text null;

alter table if exists public.workspace_guest_qa_logs
  add column if not exists user_name text null;

alter table if exists public.workspace_guest_qa_logs
  add column if not exists user_username text null;

create index if not exists workspace_guest_qa_logs_created_idx
  on public.workspace_guest_qa_logs (created_at desc);

create index if not exists workspace_guest_qa_logs_user_created_idx
  on public.workspace_guest_qa_logs (user_id, created_at desc);

create index if not exists workspace_guest_qa_logs_auth_created_idx
  on public.workspace_guest_qa_logs (auth_mode, created_at desc);

create or replace view public.workspace_user_history as
select
  u.user_id,
  u.email,
  u.clerk_username,
  u.display_name,
  u.first_seen_at,
  u.last_seen_at,
  count(c.id) as consultations_count,
  max(c.updated_at) as last_consultation_at
from public.workspace_users u
left join public.workspace_consultations c on c.user_id = u.user_id
group by
  u.user_id,
  u.email,
  u.clerk_username,
  u.display_name,
  u.first_seen_at,
  u.last_seen_at;

do $$
begin
  if exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'workspace_signed_user_qa_logs'
      and c.relkind = 'v'
  ) then
    execute 'drop view public.workspace_signed_user_qa_logs';
  end if;
end
$$;

create table if not exists public.workspace_signed_user_qa_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  auth_mode text not null default 'signed-in',
  user_id text not null default '',
  user_email text null,
  user_name text null,
  user_username text null,
  client_ip text not null default '',
  question text not null default '',
  answer text not null default '',
  rag_note text not null default '',
  finish_reason text not null default '',
  rag_source_count integer not null default 0,
  provider text not null default '',
  model text not null default '',
  metadata jsonb not null default '{}'::jsonb
);

alter table if exists public.workspace_signed_user_qa_logs
  add column if not exists auth_mode text not null default 'signed-in';

alter table if exists public.workspace_signed_user_qa_logs
  add column if not exists user_id text not null default '';

alter table if exists public.workspace_signed_user_qa_logs
  add column if not exists user_email text null;

alter table if exists public.workspace_signed_user_qa_logs
  add column if not exists user_name text null;

alter table if exists public.workspace_signed_user_qa_logs
  add column if not exists user_username text null;

create index if not exists workspace_signed_user_qa_logs_created_idx
  on public.workspace_signed_user_qa_logs (created_at desc);

create index if not exists workspace_signed_user_qa_logs_user_created_idx
  on public.workspace_signed_user_qa_logs (user_id, created_at desc);

create index if not exists workspace_signed_user_qa_logs_auth_created_idx
  on public.workspace_signed_user_qa_logs (auth_mode, created_at desc);

create or replace function public.workspace_route_guest_to_signed_qa_logs()
returns trigger
language plpgsql
as $$
begin
  if (
    coalesce(nullif(new.user_id, ''), '') <> ''
    or lower(coalesce(new.auth_mode, '')) in ('signed-in', 'authenticated')
  ) then
    insert into public.workspace_signed_user_qa_logs (
      created_at,
      auth_mode,
      user_id,
      user_email,
      user_name,
      user_username,
      client_ip,
      question,
      answer,
      rag_note,
      finish_reason,
      rag_source_count,
      provider,
      model,
      metadata
    ) values (
      coalesce(new.created_at, now()),
      case
        when lower(coalesce(new.auth_mode, '')) in ('signed-in', 'authenticated')
          then lower(coalesce(new.auth_mode, ''))
        else 'signed-in'
      end,
      coalesce(nullif(new.user_id, ''), ''),
      new.user_email,
      new.user_name,
      new.user_username,
      new.client_ip,
      new.question,
      new.answer,
      new.rag_note,
      new.finish_reason,
      coalesce(new.rag_source_count, 0),
      new.provider,
      new.model,
      coalesce(new.metadata, '{}'::jsonb)
    );
    return null;
  end if;
  return new;
end
$$;

drop trigger if exists trg_workspace_guest_to_signed_qa_logs
on public.workspace_guest_qa_logs;

create trigger trg_workspace_guest_to_signed_qa_logs
before insert on public.workspace_guest_qa_logs
for each row
execute function public.workspace_route_guest_to_signed_qa_logs();

create or replace view public.workspace_signed_user_qa_logs_enriched as
select
  q.id as log_id,
  q.created_at,
  q.auth_mode,
  q.user_id,
  coalesce(nullif(q.user_name, ''), u.display_name, '') as full_name,
  split_part(coalesce(nullif(q.user_name, ''), u.display_name, ''), ' ', 1) as first_name,
  nullif(
    trim(
      regexp_replace(
        coalesce(nullif(q.user_name, ''), u.display_name, ''),
        '^\S+\s*',
        ''
      )
    ),
    ''
  ) as last_name,
  coalesce(nullif(q.user_email, ''), u.email, '') as email,
  coalesce(nullif(q.user_username, ''), u.clerk_username, '') as username,
  q.question,
  q.answer,
  q.rag_note,
  q.finish_reason,
  q.rag_source_count,
  q.provider,
  q.model,
  q.metadata
from public.workspace_signed_user_qa_logs q
left join public.workspace_users u on u.user_id = q.user_id;

insert into public.workspace_signed_user_qa_logs (
  created_at,
  auth_mode,
  user_id,
  user_email,
  user_name,
  user_username,
  client_ip,
  question,
  answer,
  rag_note,
  finish_reason,
  rag_source_count,
  provider,
  model,
  metadata
)
select
  g.created_at,
  case
    when lower(coalesce(g.auth_mode, '')) in ('signed-in', 'authenticated') then lower(g.auth_mode)
    else 'signed-in'
  end as auth_mode,
  coalesce(nullif(g.user_id, ''), ''),
  g.user_email,
  g.user_name,
  g.user_username,
  g.client_ip,
  g.question,
  g.answer,
  g.rag_note,
  g.finish_reason,
  g.rag_source_count,
  g.provider,
  g.model,
  g.metadata
from public.workspace_guest_qa_logs g
where
  (
    (
      g.user_id is not null
      and btrim(g.user_id) <> ''
    )
    or lower(coalesce(g.auth_mode, '')) in ('signed-in', 'authenticated')
  )
  and not exists (
    select 1
    from public.workspace_signed_user_qa_logs s
    where s.user_id = coalesce(nullif(g.user_id, ''), '')
      and s.question = g.question
      and s.answer = g.answer
      and s.created_at = g.created_at
  );

delete from public.workspace_guest_qa_logs g
where
  (
    (
      g.user_id is not null
      and btrim(g.user_id) <> ''
    )
    or lower(coalesce(g.auth_mode, '')) in ('signed-in', 'authenticated')
  );
